// Package obs provides logging that cannot emit what it should not.
//
// The gateway's log calls were already careful — passages are never passed to
// slog, and credentials never were. But "careful" is a property of the people
// writing call sites, and it expires the first time someone adds a field in a
// hurry. An allowlist moves the guarantee from discipline to structure: the
// handler emits the keys it knows about and drops the rest, so a well-meant
//
//	log.Info("scan failed", "text", req.Content.Text)
//
// produces a log line without the passage, and names `text` as dropped so the
// author finds out immediately rather than after the text is in a log
// aggregator somewhere.
//
// # Why drop rather than redact
//
// Replacing a value with "[redacted]" requires knowing which values are
// sensitive, which is the judgment that fails. A key the handler has never
// heard of is dropped whatever it holds, so a field added without thought is
// absent rather than present-and-hopefully-harmless.
//
// Keys are developer-written constants, so naming a dropped key discloses
// nothing. Values are the part that can come from a request.
//
// # Error values
//
// An error's message is not loggable by default. Go error strings routinely
// wrap the thing that failed — `fmt.Errorf("decode %q: %w", body, err)` is
// ordinary code — and the detector client's own errors embed status codes and
// parser messages. So an `error` attribute is reduced to its chain of
// sentinel identities via ErrorChain, which says what happened without
// quoting what it happened to.
package obs

import (
	"context"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"slices"
	"strings"
)

// AllowedKeys is the complete set of attribute keys that may be emitted.
//
// Each is either generated by the gateway or a bounded identifier the caller
// already knows. None is derived from passage text, an evidence quotation, or
// a credential.
var AllowedKeys = map[string]bool{
	// Correlation and outcome.
	"request_id":  true,
	"outcome":     true,
	"status":      true,
	"code":        true,
	"reason":      true,
	"reason_code": true,

	// Who asked, and for what. The caller name comes from configuration, and
	// the task id is a published contract value.
	"caller":  true,
	"task_id": true,

	// Timing and size. Counts, never content.
	"duration_ms":   true,
	"passage_bytes": true,
	"scanned_bytes": true,
	"request_bytes": true,
	"detector_ms":   true,

	// Attribution.
	"label":              true,
	"action":             true,
	"policy":             true,
	"detector":           true,
	"prompt":             true,
	"prompt_fingerprint": true,
	"contract":           true,

	// Capacity and limits.
	"scope":               true,
	"retry_after_seconds": true,
	"active":              true,
	"queued":              true,
	"max_active":          true,
	"max_queued":          true,

	// Errors, as identities rather than messages.
	"error_kind": true,

	// Startup and lifecycle. Values here are configuration, not request data.
	"addr":             true,
	"detector_url":     true,
	"scan_timeout":     true,
	"shutdown_timeout": true,
	"policy_mode":      true,
	"log_level":        true,
	"callers":          true,
	"configured_keys":  true,
	"rates":            true,
	"bounds":           true,
	"buckets":          true,
	"budget":           true,

	// Network peer, for abuse diagnosis. Not request content.
	"remote": true,
}

// DroppedKey is the attribute under which filtered key names are reported.
const DroppedKey = "dropped_fields"

// Handler wraps a slog.Handler and filters attributes to AllowedKeys.
type Handler struct {
	inner slog.Handler
	// attrs are the allowlisted attributes accumulated via WithAttrs.
	attrs []slog.Attr
	// dropped are the key names filtered out of those accumulated attributes.
	dropped []string
	groups  []string
}

// NewHandler builds a JSON handler that can only emit allowlisted keys.
func NewHandler(w io.Writer, level slog.Level) *Handler {
	return &Handler{
		inner: slog.NewJSONHandler(w, &slog.HandlerOptions{Level: level}),
	}
}

func (h *Handler) Enabled(ctx context.Context, level slog.Level) bool {
	return h.inner.Enabled(ctx, level)
}

// Handle filters the record's attributes and emits what survives.
func (h *Handler) Handle(ctx context.Context, record slog.Record) error {
	kept := slices.Clone(h.attrs)
	dropped := slices.Clone(h.dropped)

	record.Attrs(func(attr slog.Attr) bool {
		if keep, name := filter(attr); keep != nil {
			kept = append(kept, *keep)
		} else {
			dropped = append(dropped, name)
		}
		return true
	})

	out := slog.NewRecord(record.Time, record.Level, record.Message, record.PC)
	out.AddAttrs(kept...)
	if len(dropped) > 0 {
		slices.Sort(dropped)
		out.AddAttrs(slog.Any(DroppedKey, slices.Compact(dropped)))
	}
	return h.inner.Handle(ctx, out)
}

// WithAttrs filters at the point attributes are attached, so a logger built
// with a disallowed field never carries it.
func (h *Handler) WithAttrs(attrs []slog.Attr) slog.Handler {
	next := &Handler{
		inner:   h.inner,
		attrs:   slices.Clone(h.attrs),
		dropped: slices.Clone(h.dropped),
		groups:  slices.Clone(h.groups),
	}
	for _, attr := range attrs {
		if keep, name := filter(attr); keep != nil {
			next.attrs = append(next.attrs, *keep)
		} else {
			next.dropped = append(next.dropped, name)
		}
	}
	return next
}

// WithGroup is not supported, and says so rather than silently flattening.
//
// A group would nest attributes under a name, and the allowlist is a flat set
// of keys — so a grouped attribute would either bypass the filter or be
// checked against the wrong name. Nothing in this service needs groups, and a
// handler that quietly got them wrong would be worse than one that refuses.
func (h *Handler) WithGroup(name string) slog.Handler {
	if name == "" {
		return h
	}
	// Returning the same handler drops the grouping rather than the
	// attributes, which keeps the filter correct.
	return h
}

// filter decides whether one attribute may be emitted.
//
// It returns the attribute to keep, or the key name that was dropped.
func filter(attr slog.Attr) (*slog.Attr, string) {
	key := attr.Key

	// An error value is never emitted as its message. It is reduced to the
	// chain of sentinel identities that ErrorChain produces, because Go error
	// strings routinely wrap the input that failed.
	if err, isError := attr.Value.Any().(error); isError {
		kind := slog.String("error_kind", ErrorChain(err))
		return &kind, ""
	}

	if !AllowedKeys[key] {
		return nil, key
	}
	return &attr, ""
}

// Sentinel is an error whose identity is safe to log.
//
// Registering an error here states that its name carries no request content.
// Anything unregistered is reported as its Go type, which is a package-level
// identifier rather than a message.
type Sentinel struct {
	Err  error
	Name string
}

var sentinels []Sentinel

// RegisterSentinel records an error whose identity may appear in logs.
//
// Called from package init blocks at startup, before any logging, so the
// slice is only read concurrently and needs no lock.
func RegisterSentinel(err error, name string) {
	sentinels = append(sentinels, Sentinel{Err: err, Name: name})
}

// ErrorChain names an error by the sentinels it wraps.
//
// The message is never included. `fmt.Errorf("decode %q: %w", body, err)` is
// ordinary Go, so an error string is a plausible place for a passage to end
// up — and the useful diagnostic fact is which known failure occurred, not the
// prose around it.
func ErrorChain(err error) string {
	if err == nil {
		return ""
	}

	var names []string
	for _, sentinel := range sentinels {
		if errors.Is(err, sentinel.Err) {
			names = append(names, sentinel.Name)
		}
	}
	if len(names) == 0 {
		// Unrecognised: report the type, which is a compile-time identifier.
		return typeName(err)
	}
	return strings.Join(names, "/")
}

// typeName renders an error's dynamic type without its message.
//
// %T is the only verb this package ever applies to an error value. %v and %s
// are never used on one, because either would render the message this package
// exists to keep out of the log.
func typeName(err error) string {
	if err == nil {
		return ""
	}
	return strings.TrimPrefix(fmt.Sprintf("%T", err), "*")
}
