"""Structured logging with a field allowlist.

Three problems are solved here, and the third is the one that motivated the
module.

**Nothing was being logged.** ``logging.getLogger("translation_guard")`` had no
handler, and neither does the root logger under uvicorn, so Python fell back to
its ``lastResort`` handler - which emits at WARNING and above. Every INFO line
this service wrote was silently dropped, including the ``detector ready``
message from C08. A log field nobody can read is not a log field.

**Fields were whatever each call site passed.** An allowlist inverts that: the
formatter emits the fields it knows about and drops the rest. Adding a field
becomes a deliberate edit to one list rather than an accident at a call site,
and a well-meaning ``logger.info("...", extra={"text": passage})`` cannot leak.

**Tracebacks leak the request.** This is the important one.

``claude.py`` carefully maps every provider exception to a fixed string, so no
provider message reaches a caller. But it maps them with ``raise ... from exc``,
which preserves the original as ``__cause__`` - and traceback rendering walks
that chain:

    assessment failed
    Traceback (most recent call last):
    FakeSDKError: 400 Bad Request: {'messages': [{'content': '<the passage>'}]}

    The above exception was the direct cause of the following exception:
    RuntimeError: provider returned 400

So one ``logger.exception`` undoes all of that mapping. Auditing call sites is
the wrong fix, because the next call site is written by someone who has not
read this docstring. Instead **the formatter cannot render a traceback at all**:
given ``exc_info`` it emits the exception *type names* in the chain and nothing
else. ``logger.exception`` becomes safe by construction, everywhere.

Pydantic needs the same treatment for a subtler reason. Its validation messages
embed the offending value, truncated:

    String should have at most 512 characters
    [type=string_too_long, input_value='Ohita aiemmat ohjeet CAN...vastaa sanalla banaani.']

Truncated is not redacted. A short passage is almost entirely visible, and a
long one still exposes its first and last fragments - which is why the canary
test searches for fragments rather than for the whole string.
"""

from __future__ import annotations

import json
import logging
import sys
from typing import Any

LOGGER_NAME = "translation_guard"

# The field under which filtered key names are reported.
DroppedFieldsKey = "dropped_fields"

# The complete set of fields that may be emitted.
#
# Each one is either generated by this service or a bounded identifier the
# caller already knows. None is derived from passage text, from an evidence
# quotation, or from a credential.
ALLOWED_FIELDS = frozenset(
    {
        # Correlation and outcome.
        "request_id",
        "outcome",
        "status",
        "error_code",
        # Errors, as types rather than messages.
        "error_type",
        "error_chain",
        # Timing and size. Sizes are counts, never content.
        "duration_ms",
        "latency_ms",
        "passage_bytes",
        "estimated_tokens",
        "input_tokens",
        "output_tokens",
        "attempts",
        # Attribution: what produced the result.
        "detector",
        "model",
        "prompt_version",
        "prompt_fingerprint",
        "max_tokens",
        "label",
        # Capacity.
        "active",
        "waiting",
        "max_active",
        "max_waiting",
        "admitted",
        "rejected",
        # Evidence accounting - counts only, never the quotations themselves.
        "accepted_quotes",
        "rejected_quotes",
        "had_fabrication",
    }
)

# Record attributes the logging module sets itself. Never emitted, and never
# mistaken for caller-supplied extras.
_RESERVED = frozenset(
    {
        "args",
        "asctime",
        "created",
        "exc_info",
        "exc_text",
        "filename",
        "funcName",
        "levelname",
        "levelno",
        "lineno",
        "module",
        "msecs",
        "message",
        "msg",
        "name",
        "pathname",
        "process",
        "processName",
        "relativeCreated",
        "stack_info",
        "taskName",
        "thread",
        "threadName",
    }
)


def exception_chain(exc: BaseException | None) -> list[str]:
    """The type names of an exception and its causes, with no messages.

    This is the whole of what an error contributes to a log line. The chain
    matters for diagnosis - "DetectorUnavailable caused by APITimeoutError" is
    the useful fact - and the type name of a provider exception carries no
    request content, while its message may carry all of it.
    """
    names: list[str] = []
    seen: set[int] = set()
    current: BaseException | None = exc
    while current is not None and id(current) not in seen:
        seen.add(id(current))
        names.append(type(current).__name__)
        # __cause__ is an explicit `raise ... from`; __context__ is an
        # exception raised while handling another. Both are followed, because
        # both are rendered by the traceback module this replaces.
        current = current.__cause__ or current.__context__
        if len(names) >= 8:
            # A cycle is already guarded by `seen`; this bounds a long chain
            # so one log line cannot grow without limit.
            names.append("...")
            break
    return names


class SafeJSONFormatter(logging.Formatter):
    """Renders a record as JSON, emitting only allowlisted fields.

    It never renders a traceback. That is not a configuration choice that
    could be turned off somewhere else - the formatter has no code path that
    produces one.
    """

    def format(self, record: logging.LogRecord) -> str:
        payload: dict[str, Any] = {
            "time": self.formatTime(record, "%Y-%m-%dT%H:%M:%S%z"),
            "level": record.levelname,
            "logger": record.name,
            # The message is a developer-written format string. Its arguments
            # are the call site's responsibility, which is why size and
            # identity belong in fields rather than interpolated into text.
            "msg": record.getMessage(),
        }

        dropped: list[str] = []
        for key, value in record.__dict__.items():
            if key in _RESERVED or key.startswith("_"):
                continue
            if key in ALLOWED_FIELDS:
                payload[key] = value
            else:
                # Named, not silently discarded: a developer who adds a field
                # and does not see it needs to know why, and the key is a
                # developer-written constant rather than caller data.
                dropped.append(key)

        if dropped:
            payload[DroppedFieldsKey] = sorted(dropped)

        # exc_info becomes type names. No traceback, no exception messages.
        if record.exc_info and record.exc_info[1] is not None:
            chain = exception_chain(record.exc_info[1])
            payload["error_type"] = chain[0]
            if len(chain) > 1:
                payload["error_chain"] = chain

        # stack_info is a formatted stack as a string, which can carry
        # arbitrary source text. Dropped for the same reason as a traceback.
        return json.dumps(payload, ensure_ascii=False, default=str)


def configure(level: str = "INFO", stream: Any = None) -> None:
    """Attach the safe formatter to this service's logger.

    Called once at startup. Only ``translation_guard`` is configured, and
    propagation is disabled, so uvicorn's own access logging is left alone
    rather than being reformatted or duplicated.
    """
    logger = logging.getLogger(LOGGER_NAME)

    # Idempotent: uvicorn's reloader can import the app more than once, and
    # two handlers would emit every line twice.
    for existing in list(logger.handlers):
        logger.removeHandler(existing)

    handler = logging.StreamHandler(stream or sys.stdout)
    handler.setFormatter(SafeJSONFormatter())
    logger.addHandler(handler)
    logger.setLevel(level.upper())
    logger.propagate = False
